
canvas:




  canvas_names:
    - canvas_small
    - canvas_medium

  canvas_small:
    x_pos_1: 160
    y_pos_1: 116
    z_pos_1: -201

    x_pos_2: 144
    y_pos_2: 131
    z_pos_2: -201

    x_tp: 151
    y_tp: 121
    z_tp: -215

    width: 16
    height : 16

  canvas_medium:

    x_pos_1: 297
    y_pos_1: 163
    z_pos_1: -252

    x_pos_2: 144
    y_pos_2: 195
    z_pos_2: -252

    x_tp: 313
    y_tp: 181
    z_tp: -276

    width: 32
    height: 32
