

plugin-prefix: "&8&l[&3Canvas&bMap&8&l] §r"


npc:
  select-canvas:
    item-slot:
      11:
        name: "&1&lSmall Map"

        lore-1: "&916*16 &7blocks"
        lore-2: "&6%empty-canvas-amount% &7empty Canvases"
        lore-3: ""

        price: 50
        canvas-size: 16

      15:
        name: "&5&lBig Map"

        lore-1: "&d32*32 &7blocks"
        lore-2: "&6%empty-canvas-amount% &7empty Canvases"
        lore-3: ""

        price: 100
        canvas-size: 32

  save-canvas:
    item-slot:
      12:
        material: "EMERALD"
        name: "&2&lBuy"

        lore-1: ""
        lore-2: ""
        lore-3: ""

      14:
        material: "BARRIER"
        name: "&c&lExit"

        lore-1: "&4Your Painting will not be saved!"
        lore-2: ""
        lore-3: ""